### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Message data must be an object! Was: undefined

### ISSUE THREAD

**Issue by PastaGringo** [streamr-dev/helium-mqtt-adapter#1]
Hi,

Thanks for the blog post I'm trying to setup everything with Helium to discover Streamr.

I think followed everything : 
- Added the LHT65 to my Helium console with decoder function attached (from [this](https://gist.github.com/hpihkala/2f949b32cf035397684f544bd5021363) link) 
- Created the MQTT integration with the Stream ID retrieved from Streamer Core attached to the LHT65
- On Ubuntu 20.04, installed nodejs v14.16.1 and npm v6.14.12, Git cloned the repo and insert my Metamask private key and the user/password into the .env file (btw, why everytime you speak about the private key it begins by "0x0000 ..." or my private key begins by "123xaaa ..." ?)
- Started the adapter with "`npm" start`"

When a request is sent from the Helium console to my server where the adapter is installed I can see this error message: 

```
/helium-mqtt-adapter$ npm start

> trusted-mqtt-adapter@1.0.0 start /home/XXXXXX/XXXXXX/helium-mqtt-adapter
> ts-node src/index.ts

Server listening on port 1883
Client subscribed: 0xf4e7078a0dcc7c17e502d19685d99fa8743404f1/helium/puteaux/temperature
(node:525261) UnhandledPromiseRejectionWarning: Error: Message data must be an object! Was: undefined
    at MessageCreationUtil._callee4$ (/home/XXXXXX/XXXXXX/helium-mqtt-adapter/node_modules/streamr-client/dist/webpack:/StreamrClient/src/MessageCreationUtil.js:115:19)
    at tryCatch (/home/XXXXXX/XXXXXX/helium-mqtt-adapter/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/XXXXXX/XXXXXX/helium-mqtt-adapter/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/home/XXXXXX/XXXXXX/helium-mqtt-adapter/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/home/XXXXXX/XXXXXX/helium-mqtt-adapter/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/XXXXXX/XXXXXX/helium-mqtt-adapter/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /home/XXXXXX/XXXXXX/helium-mqtt-adapter/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at MessageCreationUtil.<anonymous> (/home/XXXXXX/XXXXXX/helium-mqtt-adapter/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
    at MessageCreationUtil.createStreamMessage (/home/XXXXXX/XXXXXX/helium-mqtt-adapter/node_modules/streamr-client/dist/streamr-client.nodejs.js:6522:37)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:525261) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:525261) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I can see the request is well sent from the Helium console to my server ("Success" from the uplink in Helium console)
I guess this error blocks the transmission to Streamr and I can't see any data from the Stream.

Do I forgot something ?
Thanks for the help!

**Comment by kare** [comment]
@PastaGringo Thanks for the issue report. Does PR https://github.com/streamr-dev/helium-mqtt-adapter/pull/2 solve your issue?

**Comment by PastaGringo** [comment]
Yes, I made the modifications and it's working now !
Thanks :)
